# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designerUI03.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1010, 658)
        self.test_bt = QtWidgets.QPushButton(Form)
        self.test_bt.setGeometry(QtCore.QRect(170, 540, 111, 61))
        self.test_bt.setObjectName("test_bt")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(350, 30, 121, 20))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(610, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.datawidget = MplWidget(Form)
        self.datawidget.setGeometry(QtCore.QRect(30, 110, 451, 401))
        self.datawidget.setObjectName("datawidget")
        self.costwidget = mplwidget2(Form)
        self.costwidget.setGeometry(QtCore.QRect(520, 90, 261, 241))
        self.costwidget.setObjectName("costwidget")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(830, 90, 161, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filenamelabel = QtWidgets.QLabel(self.layoutWidget)
        self.filenamelabel.setObjectName("filenamelabel")
        self.verticalLayout.addWidget(self.filenamelabel)
        self.openbt = QtWidgets.QPushButton(self.layoutWidget)
        self.openbt.setObjectName("openbt")
        self.verticalLayout.addWidget(self.openbt)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(850, 180, 127, 47))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.learninglabel = QtWidgets.QLabel(self.layoutWidget1)
        self.learninglabel.setObjectName("learninglabel")
        self.verticalLayout_2.addWidget(self.learninglabel)
        self.learninginput = QtWidgets.QLineEdit(self.layoutWidget1)
        self.learninginput.setObjectName("learninginput")
        self.verticalLayout_2.addWidget(self.learninginput)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(850, 250, 127, 47))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.iterationlabel = QtWidgets.QLabel(self.layoutWidget2)
        self.iterationlabel.setObjectName("iterationlabel")
        self.verticalLayout_3.addWidget(self.iterationlabel)
        self.iterationinput = QtWidgets.QLineEdit(self.layoutWidget2)
        self.iterationinput.setObjectName("iterationinput")
        self.verticalLayout_3.addWidget(self.iterationinput)
        self.train_bt = QtWidgets.QPushButton(Form)
        self.train_bt.setGeometry(QtCore.QRect(40, 540, 111, 61))
        self.train_bt.setObjectName("train_bt")
        self.accuracywidget = mplwidget2(Form)
        self.accuracywidget.setGeometry(QtCore.QRect(520, 390, 261, 241))
        self.accuracywidget.setObjectName("accuracywidget")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(600, 340, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(220, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.test_acc_show = QtWidgets.QLabel(Form)
        self.test_acc_show.setGeometry(QtCore.QRect(320, 550, 191, 41))
        self.test_acc_show.setObjectName("test_acc_show")
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(850, 320, 127, 47))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hiddenlabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.hiddenlabel.setObjectName("hiddenlabel")
        self.verticalLayout_4.addWidget(self.hiddenlabel)
        self.hiddeninput = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.hiddeninput.setObjectName("hiddeninput")
        self.verticalLayout_4.addWidget(self.hiddeninput)
        self.layoutWidget_3 = QtWidgets.QWidget(Form)
        self.layoutWidget_3.setGeometry(QtCore.QRect(850, 390, 127, 47))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.l2label = QtWidgets.QLabel(self.layoutWidget_3)
        self.l2label.setObjectName("l2label")
        self.verticalLayout_5.addWidget(self.l2label)
        self.l2input = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.l2input.setObjectName("l2input")
        self.verticalLayout_5.addWidget(self.l2input)
        self.layoutWidget_4 = QtWidgets.QWidget(Form)
        self.layoutWidget_4.setGeometry(QtCore.QRect(850, 460, 127, 47))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.batchlabel = QtWidgets.QLabel(self.layoutWidget_4)
        self.batchlabel.setObjectName("batchlabel")
        self.verticalLayout_6.addWidget(self.batchlabel)
        self.batchinput = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.batchinput.setObjectName("batchinput")
        self.verticalLayout_6.addWidget(self.batchinput)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.test_bt.setText(_translate("Form", "test"))
        self.label_3.setText(_translate("Form", "Neural Networks HW2 : MLP"))
        self.label_5.setText(_translate("Form", "104103025 許嘉茵"))
        self.label_7.setText(_translate("Form", "cost"))
        self.filenamelabel.setText(_translate("Form", "filename"))
        self.openbt.setText(_translate("Form", "Open file"))
        self.learninglabel.setText(_translate("Form", "learning rate"))
        self.iterationlabel.setText(_translate("Form", "iteration times"))
        self.train_bt.setText(_translate("Form", "train"))
        self.label_8.setText(_translate("Form", "accuracy"))
        self.label_9.setText(_translate("Form", "data"))
        self.test_acc_show.setText(_translate("Form", "Test accuracy"))
        self.hiddenlabel.setText(_translate("Form", "hidden layer"))
        self.l2label.setText(_translate("Form", "L2_parameter"))
        self.batchlabel.setText(_translate("Form", "batch_size"))

from mplwidget import MplWidget
from mplwidget2 import mplwidget2
